// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXrbUBI6kSupL_75lG-KVNhrvL6-Ef3zM',
    appId: '1:920376012280:web:a6de35eff5a061a480ba0d',
    messagingSenderId: '920376012280',
    projectId: 'diaryapps-6320a',
    authDomain: 'diaryapps-6320a.firebaseapp.com',
    storageBucket: 'diaryapps-6320a.appspot.com',
    measurementId: 'G-QJSRYQ0GEJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB95Wrey-i3t2GhIsSb58g9DyHIJy2wVrM',
    appId: '1:920376012280:android:0f72cc47462297ef80ba0d',
    messagingSenderId: '920376012280',
    projectId: 'diaryapps-6320a',
    storageBucket: 'diaryapps-6320a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCylDNNzaqNZM2UesEAURrJbdd73IZCGHU',
    appId: '1:920376012280:ios:310020bb2278905980ba0d',
    messagingSenderId: '920376012280',
    projectId: 'diaryapps-6320a',
    storageBucket: 'diaryapps-6320a.appspot.com',
    iosClientId: '920376012280-033fe7hvhlnuv13jet197a9379jp19u7.apps.googleusercontent.com',
    iosBundleId: 'com.example.diaryapps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCylDNNzaqNZM2UesEAURrJbdd73IZCGHU',
    appId: '1:920376012280:ios:c0f330fc8005f51080ba0d',
    messagingSenderId: '920376012280',
    projectId: 'diaryapps-6320a',
    storageBucket: 'diaryapps-6320a.appspot.com',
    iosClientId: '920376012280-nickcru8v87kl5fjjr30hfvgv6f8btf7.apps.googleusercontent.com',
    iosBundleId: 'com.example.diaryapps.RunnerTests',
  );
}
